Update for Swift 5.10 and strict concurrency
vapor/template pull request #125
Opened 2024-03-10 19:53 UTC by gwynne

Updates the template for Swift 5.10, removes strict concurrency warnings, and enables them by default. This PR is an extended version of the work started in #124.

Shoutout and thanks to @ameter for the initial work on this!

2024-03-12 11:31 UTC, MahdiBM approved these changes

2024-03-12 11:31 UTC, MahdiBM commented on Package.swift
> +                // Workaround for https://github.com/apple/swift-package-manager/issues/6940
is this not fixed on 5.10?

2024-03-14 00:34 UTC, 0xTim requested changes
We can remove the manifest workaround as that works in 5.10

2024-03-14 00:34 UTC, 0xTim commented on Package.swift
> +                // Workaround for https://github.com/apple/swift-package-manager/issues/6940
I believe so, yes

2024-04-09 15:21 UTC, 0xTim commented
Closing in favour of #127

2024-04-09 15:21 UTC, closed without merging